### ISSUE TITLE
SSL/TLS?

### ISSUE THREAD

**Issue by leetrout** [rottytooth/rot8000#20]
Any chance of tossing a cert up?

**Comment by rottytooth** [comment]
I would like to but would need to work out a different hosting strategy -- it's currently one site serving content for a number of small projects based on hostname.

**Comment by leetrout** [comment]
Well if there's anything I could do (other than forking and tossing it on GH pages 😂 ) to help let me know!

**Comment by rottytooth** [comment]
Thanks! I'm going to give this some thought

**Comment by Gunni** [comment]
Hey, if you migrate dns to cloudflare they do ssl/tls for you for free.

Just a thought.

**Comment by rottytooth** [comment]
I would still need to register the cert with IIS, though, and my hosting company doesn't support certs for different domains on the same site. Right now, I have a single acct that serves content for what's really six different sites (danieltemkin.com, metriclock.com, some other projects) by hostname. If I register the cert for one site then the others will cause security warnings for the other domains. 

This was fine as a hosting strategy when ssl was less important. But at this point, the purely JS-based sites like rot8000 will probably need to be moved elsewhere.

**Comment by Gunni** [comment]
@rottytooth that's not correct, if you configure cloudflare in Flexible mode then connections to Cloudflare are encrypted, but from Cloudflare to the backend are in plaintext. No server config change required at all.

**Comment by rottytooth** [comment]
@Gunni : Thank you, this solves the problem; https is live now
