### ISSUE TITLE
Can i has npm module?

### ISSUE THREAD

**Issue by insanity54** [rottytooth/rot8000#21]
I would like to 

```
const rot8000 = require('rot8000');
const output = rot8000('my funny text')
```

but there is no npm module.

I think package.json is incomplete for publishing to npm. I would fill it out if this project is accepting PRs

greets from Mars

**Comment by insanity54** [comment]
I accidentally published an npm module named, 'rot8000'. As this is not my project, I don't feel right taking that name. I meant to prefix it with something. I'm unpublishing rot8000 and it will be available again in 24 hours.

**Comment by rottytooth** [comment]
Okay thanks -- feel free to create a PR -- otherwise, I will look into an npm module (probably not for a few weeks)

**Comment by rottytooth** [comment]
Beautiful! Thanks
