### ISSUE TITLE
Stack Trace Enabled in Production

### ISSUE THREAD

**Issue by lachlan-smith** [rottytooth/rot8000#3]
When entering a potentially dangerous request, the web app will display a full ASP.NET stack trace.

To replicate the issue, try to encode `<html>` using the cypher, this will generate a ASP.NET stack trace, along with .NET debugging information.

**Comment by rottytooth** [comment]
Ok, while normally I enjoy debugging on Live, I agree that business-critical encryption like rot8000 needs to stay secure. I've updated my web.config and also swallow security errors. Nothing to check in here, however, as I don't have the web app itself in this repo
